---
---Generated By proto-gen. Do not Edit.
---
ProtocolIds = {
    Phone                         =			13503,
    Phone3                        =			13504,
}
ProtocolNames = {
    [13503]                       =			"Data.PB.Phone",
    [13504]                       =			"Data.PB.Phone3",
}
